baseURL: https://zhaoshanduan.com/

languageCode: en-us
defaultContentLanguage: en
title: "Zhaoshan Duan"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
#  ch:
#    LanguageName: 中文
#    weight: 2

# Control TOC depth and allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable Google Analytics
googleAnalytics: G-8DDPXZQE1K

# Enable global emoji support
enableEmoji: true

# ignore these types of files
ignore:
  - "*.Rmd"

# Site parameters
params:
  # Background image of the landing page
  # background: /images/site/cool-background.png
  background: /images/site/dark_background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will default to the theme logos if not provided.
  logo:
    main: /images/site/joshua_tree.png
    inverted: /images/site/joshua_tree.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/Zhaoshan-Duan/zhaoshanduan.com
  # Default branch of your Git repo
  gitBranch: source

  # Configure Notes property
  notes:
    # Set a background color of note card header. Use any CSS color code/name.
    headerBackground: aliceblue
    # Set note card title color.
    headerTextColor: #1c2d41

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

custom_css: "css/custom.css"
