title = "Zhaoshan Duan"
baseURL = "https://zhaoshanduan.com/"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "anatole"
summarylength = 10
copyright = "&copy; Julia Silge {year}"
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "I'm Zhaoshan Duan"
author = "Zhaoshan Duan"
copyright = "2020-2021"
description = "Call me Joshua"
profilePicture = "images/masked.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["blog"]
images = ["images/masked.jpg"]
doNotLoadAnimations = false
displayMode = ""
disableThemeSwitcher = false

# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true


[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/zhaoshan-duan-37bab885/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Zhaoshan-Duan"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/JoshuaD924"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "joshua.duan47@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

#  [[menu.main]]
#  name = "Resume"
#  weight = 400
#  identifier = "Resume"
#  url = "/resume/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "Projects"
  url = "/projects/"

  [[menu.main]]
  name = "Creative"
  weight = 400
  identifier = "Creative"
  url = "/creative/"
  
  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"
